version: "3.7"
services:
  sdk:
    container_name: sdk
    build: .
    # image: ochom/sdp-sdk:latest
    ports:
      - "8088:5000"
    environment:
      PORT: 5000
      DEPLOYMENT_MODE: test
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    volumes:
      - ./certs:/app/ssl
