name: Build and Deploy
on:
  push:
    branches:
      - cr

env:
  IMAGE_NAME: safaricom-sdp
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GCP_KEYS_JSON: ${{ secrets.GCP_KEYS_JSON }}

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate GCP
        uses: google-github-actions/auth@v0.8.0
        with:
          credentials_json: ${{ env.GCP_KEYS_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

      - name: Create Tags
        id: tags
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: ${{ steps.tags.outputs.sha_short }}
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

      - name: "Deploy to Cloud Run"
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.10.0
        with:
          image: "gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest"
          service: ${{ env.IMAGE_NAME }}
          region: europe-west2
          env_vars: |
            DEPLOYMENT_MODE=production
            ACCESS_TOKEN=${{ secrets.PROD_ACCESS_TOKEN }}

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
