name: Docker Hub Push

on:
  push:
    branches:
      - docker-hub

env:
  IMAGE_NAME: ochom/sdp-sdk:latest

jobs:
  push_to_registry:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build
        run: docker build -t  $IMAGE_NAME  .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Push
        run: docker push $IMAGE_NAME
